import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:motivaid/core/auth/models/auth_state.dart';
import 'package:motivaid/core/auth/providers/auth_provider.dart';
import 'package:motivaid/core/units/models/unit_membership.dart';
import 'package:motivaid/core/units/repositories/unit_membership_repository.dart';
import 'package:motivaid/core/units/repositories/supabase_unit_membership_repository.dart';

/// Unit membership repository provider
final unitMembershipRepositoryProvider = Provider<UnitMembershipRepository>((ref) {
  final supabase = ref.watch(supabaseClientProvider);
  return SupabaseUnitMembershipRepository(supabase);
});

/// User's memberships provider
final userMembershipsProvider = FutureProvider<List<UnitMembership>>((ref) async {
  final repository = ref.watch(unitMembershipRepositoryProvider);
  final authState = ref.watch(authNotifierProvider);
  
  if (authState is! AuthStateAuthenticated) {
    return [];
  }
  
  return repository.getMembershipsByProfile(authState.user.id);
});

/// User's approved memberships only
final userApprovedMembershipsProvider = FutureProvider<List<UnitMembership>>((ref) async {
  final memberships = await ref.watch(userMembershipsProvider.future);
  return memberships.where((m) => m.isApproved).toList();
});

/// Pending memberships for a unit (for supervisors)
final pendingMembershipsByUnitProvider = FutureProvider.family<List<UnitMembership>, String>((ref, unitId) async {
  final repository = ref.watch(unitMembershipRepositoryProvider);
  return repository.getPendingMembershipsByUnit(unitId);
});

/// All memberships for a unit
final membershipsByUnitProvider = FutureProvider.family<List<UnitMembership>, String>((ref, unitId) async {
  final repository = ref.watch(unitMembershipRepositoryProvider);
  return repository.getMembershipsByUnit(unitId);
});

/// Unit membership notifier for actions
class UnitMembershipNotifier extends StateNotifier<AsyncValue<void>> {
  final UnitMembershipRepository _repository;

  UnitMembershipNotifier(this._repository) : super(const AsyncValue.data(null));

  /// Request to join a unit
  Future<void> requestJoinUnit({
    required String profileId,
    required String unitId,
    required UserRole role,
  }) async {
    state = const AsyncValue.loading();
    try {
      final membership = UnitMembership(
        id: '',  // Will be generated by database
        profileId: profileId,
        unitId: unitId,
        role: role,
        status: MembershipStatus.pending,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );
      
      await _repository.createMembership(membership);
      state = const AsyncValue.data(null);
    } catch (e, stack) {
      state = AsyncValue.error(e, stack);
      rethrow;
    }
  }

  /// Approve a membership
  Future<void> approveMembership(String membershipId, String approvedBy) async {
    state = const AsyncValue.loading();
    try {
      await _repository.approveMembership(membershipId, approvedBy);
      state = const AsyncValue.data(null);
    } catch (e, stack) {
      state = AsyncValue.error(e, stack);
      rethrow;
    }
  }

  /// Reject a membership
  Future<void> rejectMembership(String membershipId, String reason) async {
    state = const AsyncValue.loading();
    try {
      await _repository.rejectMembership(membershipId, reason);
      state = const AsyncValue.data(null);
    } catch (e, stack) {
      state = AsyncValue.error(e, stack);
      rethrow;
    }
  }
}

/// Unit membership notifier provider
final unitMembershipNotifierProvider = StateNotifierProvider<UnitMembershipNotifier, AsyncValue<void>>((ref) {
  final repository = ref.watch(unitMembershipRepositoryProvider);
  return UnitMembershipNotifier(repository);
});
